http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.kewar.org`)"
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true