version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    environment:
      CF_API_EMAIL: "${CLOUDFLARE_EMAIL}"
      CF_DNS_API_TOKEN: ${C}
    command:
      - --api.insecure=true # Disable this in production!
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email="${CLOUDFLARE_EMAIL}"
      - --certificatesresolvers.cloudflare.acme.storage=/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # For the Traefik API/dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./config.yaml:/config.yaml:ro
      - ./acme.json:/acme.json
    networks:
      - web

networks:
  web:
