version: "3.9"

services:
  traefik:
    image: traefik:latest # Or a specific version
    container_name: traefik
    command: 
      - --api.insecure=true # Disable this in production!
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # For the Traefik API/dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./config.yaml:/config.yaml:ro
    networks:
      - web

networks:
  web: