version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    environment:
      - CF_API_EMAIL="kenrward"
      - CF_DNS_API_TOKEN="5Mmz1QWw44T4yzkAcUjMxz5Va5BgbVota8ytP6PT"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ./dynamic.yaml:/dynamic.yaml:ro
      - ./acme.json:acme.json
    networks:
      - web

networks:
  web:
