global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "kenrward@gmail.com"
      storage: "acme.json"
      dnsChallenge:
        provider: cloudflare
  tailscale: {}
log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: "dynamic.yaml"
    watch: true  
