global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${CLOUDFLARE_EMAIL}"
      storage: "acme.json"
      dnsChallenge:
        provider: cloudflare

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true
