global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "kenrward@gmail.com"      # Replace with your email
      storage: "acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: "30"

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true  # Disable this in production
