global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.kewar.org`)"
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: "kenrward@gmail.com"
      storage: "acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 30

