global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO # Change to DEBUG for more verbose logging

api:
  dashboard: true
  insecure: true # Disable this in production!

entryPoints:
  web:
    address: :80
  websecure:
    address: :443