http:
  routers:
    dashboard:
      entryPoints:
        - "https"
      rule: "Host(`traefik.kewar.org`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: dashboard
    proxmox-router:
      rule: "Host(`proxmox.kewar.org`)"
      entryPoints: ["websecure"]
      tls:
        certresolver: letsencrypt
      service: proxmox-service

  services:
    dashboard:
      loadBalancer:
        servers:
          - url: "http://192.168.86.51:8080"
        passHostHeader: true
    proxmox-service:
      loadBalancer:
        servers:
          - url: "https://192.168.86.21:8006" 

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers