http:
  routers:
    dashboard:
      entryPoints:
        - "https"
      rule: "Host(`traefik.kewar.org`) && PathPrefix(`/dashboard`)" 
      tls:
        certresolver: cloudflare 
      service: dashboard

  services:
    dashboard:
      loadBalancer:
        servers:
          - url: "http://192.168.86.51:8080" 
        passHostHeader: true

  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN