http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.yourdomain.com`)" # Replace with your domain
      entryPoints:
        - websecure
      service: api@internal
      tls: {}

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true