global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
certificatesResolvers:
  cloudflare:
    acme:
      email: $[CLOUDFLARE_ACCOUNT_EMAIL]
      storage: acme.json
      dnsChallenge:
        provider: cloudflare